version: "3.8"

services:
  coding-blog-psql-db:
    image: postgres
    container_name: coding-blog-psql-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  coding-blog-app:
    container_name: coding-blog-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - coding-blog-psql-db
